export const country = [ 
    {name: 'Afghanistan', code: 'AF'}, 
    {name: 'Åland Islands', code: 'AX'}, 
    {name: 'Albania', code: 'AL'}, 
    {name: 'Algeria', code: 'DZ'}, 
    {name: 'American Samoa', code: 'AS'}, 
    {name: 'AndorrA', code: 'AD'}, 
    {name: 'Angola', code: 'AO'}, 
    {name: 'Anguilla', code: 'AI'}, 
    {name: 'Antarctica', code: 'AQ'}, 
    {name: 'Antigua and Barbuda', code: 'AG'}, 
    {name: 'Argentina', code: 'AR'}, 
    {name: 'Armenia', code: 'AM'}, 
    {name: 'Aruba', code: 'AW'}, 
    {name: 'Australia', code: 'AU'}, 
    {name: 'Austria', code: 'AT'}, 
    {name: 'Azerbaijan', code: 'AZ'}, 
    {name: 'Bahamas', code: 'BS'}, 
    {name: 'Bahrain', code: 'BH'}, 
    {name: 'Bangladesh', code: 'BD'}, 
    {name: 'Barbados', code: 'BB'}, 
    {name: 'Belarus', code: 'BY'}, 
    {name: 'Belgium', code: 'BE'}, 
    {name: 'Belize', code: 'BZ'}, 
    {name: 'Benin', code: 'BJ'}, 
    {name: 'Bermuda', code: 'BM'}, 
    {name: 'Bhutan', code: 'BT'}, 
    {name: 'Bolivia', code: 'BO'}, 
    {name: 'Bosnia and Herzegovina', code: 'BA'}, 
    {name: 'Botswana', code: 'BW'}, 
    {name: 'Bouvet Island', code: 'BV'}, 
    {name: 'Brazil', code: 'BR'}, 
    {name: 'British Indian Ocean Territory', code: 'IO'}, 
    {name: 'Brunei Darussalam', code: 'BN'}, 
    {name: 'Bulgaria', code: 'BG'}, 
    {name: 'Burkina Faso', code: 'BF'}, 
    {name: 'Burundi', code: 'BI'}, 
    {name: 'Cambodia', code: 'KH'}, 
    {name: 'Cameroon', code: 'CM'}, 
    {name: 'Canada', code: 'CA'}, 
    {name: 'Cape Verde', code: 'CV'}, 
    {name: 'Cayman Islands', code: 'KY'}, 
    {name: 'Central African Republic', code: 'CF'}, 
    {name: 'Chad', code: 'TD'}, 
    {name: 'Chile', code: 'CL'}, 
    {name: 'China', code: 'CN'}, 
    {name: 'Christmas Island', code: 'CX'}, 
    {name: 'Cocos (Keeling) Islands', code: 'CC'}, 
    {name: 'Colombia', code: 'CO'}, 
    {name: 'Comoros', code: 'KM'}, 
    {name: 'Congo', code: 'CG'}, 
    {name: 'Congo, The Democratic Republic of the', code: 'CD'}, 
    {name: 'Cook Islands', code: 'CK'}, 
    {name: 'Costa Rica', code: 'CR'}, 
    {name: 'Cote D\'Ivoire', code: 'CI'}, 
    {name: 'Croatia', code: 'HR'}, 
    {name: 'Cuba', code: 'CU'}, 
    {name: 'Cyprus', code: 'CY'}, 
    {name: 'Czech Republic', code: 'CZ'}, 
    {name: 'Denmark', code: 'DK'}, 
    {name: 'Djibouti', code: 'DJ'}, 
    {name: 'Dominica', code: 'DM'}, 
    {name: 'Dominican Republic', code: 'DO'}, 
    {name: 'Ecuador', code: 'EC'}, 
    {name: 'Egypt', code: 'EG'}, 
    {name: 'El Salvador', code: 'SV'}, 
    {name: 'Equatorial Guinea', code: 'GQ'}, 
    {name: 'Eritrea', code: 'ER'}, 
    {name: 'Estonia', code: 'EE'}, 
    {name: 'Ethiopia', code: 'ET'}, 
    {name: 'Falkland Islands (Malvinas)', code: 'FK'}, 
    {name: 'Faroe Islands', code: 'FO'}, 
    {name: 'Fiji', code: 'FJ'}, 
    {name: 'Finland', code: 'FI'}, 
    {name: 'France', code: 'FR'}, 
    {name: 'French Guiana', code: 'GF'}, 
    {name: 'French Polynesia', code: 'PF'}, 
    {name: 'French Southern Territories', code: 'TF'}, 
    {name: 'Gabon', code: 'GA'}, 
    {name: 'Gambia', code: 'GM'}, 
    {name: 'Georgia', code: 'GE'}, 
    {name: 'Germany', code: 'DE'}, 
    {name: 'Ghana', code: 'GH'}, 
    {name: 'Gibraltar', code: 'GI'}, 
    {name: 'Greece', code: 'GR'}, 
    {name: 'Greenland', code: 'GL'}, 
    {name: 'Grenada', code: 'GD'}, 
    {name: 'Guadeloupe', code: 'GP'}, 
    {name: 'Guam', code: 'GU'}, 
    {name: 'Guatemala', code: 'GT'}, 
    {name: 'Guernsey', code: 'GG'}, 
    {name: 'Guinea', code: 'GN'}, 
    {name: 'Guinea-Bissau', code: 'GW'}, 
    {name: 'Guyana', code: 'GY'}, 
    {name: 'Haiti', code: 'HT'}, 
    {name: 'Heard Island and Mcdonald Islands', code: 'HM'}, 
    {name: 'Holy See (Vatican City State)', code: 'VA'}, 
    {name: 'Honduras', code: 'HN'}, 
    {name: 'Hong Kong', code: 'HK'}, 
    {name: 'Hungary', code: 'HU'}, 
    {name: 'Iceland', code: 'IS'}, 
    {name: 'India', code: 'IN'}, 
    {name: 'Indonesia', code: 'ID'}, 
    {name: 'Iran, Islamic Republic Of', code: 'IR'}, 
    {name: 'Iraq', code: 'IQ'}, 
    {name: 'Ireland', code: 'IE'}, 
    {name: 'Isle of Man', code: 'IM'}, 
    {name: 'Israel', code: 'IL'}, 
    {name: 'Italy', code: 'IT'}, 
    {name: 'Jamaica', code: 'JM'}, 
    {name: 'Japan', code: 'JP'}, 
    {name: 'Jersey', code: 'JE'}, 
    {name: 'Jordan', code: 'JO'}, 
    {name: 'Kazakhstan', code: 'KZ'}, 
    {name: 'Kenya', code: 'KE'}, 
    {name: 'Kiribati', code: 'KI'}, 
    {name: 'Korea, Democratic People\'S Republic of', code: 'KP'}, 
    {name: 'Korea, Republic of', code: 'KR'}, 
    {name: 'Kuwait', code: 'KW'}, 
    {name: 'Kyrgyzstan', code: 'KG'}, 
    {name: 'Lao People\'S Democratic Republic', code: 'LA'}, 
    {name: 'Latvia', code: 'LV'}, 
    {name: 'Lebanon', code: 'LB'}, 
    {name: 'Lesotho', code: 'LS'}, 
    {name: 'Liberia', code: 'LR'}, 
    {name: 'Libyan Arab Jamahiriya', code: 'LY'}, 
    {name: 'Liechtenstein', code: 'LI'}, 
    {name: 'Lithuania', code: 'LT'}, 
    {name: 'Luxembourg', code: 'LU'}, 
    {name: 'Macao', code: 'MO'}, 
    {name: 'Macedonia, The Former Yugoslav Republic of', code: 'MK'}, 
    {name: 'Madagascar', code: 'MG'}, 
    {name: 'Malawi', code: 'MW'}, 
    {name: 'Malaysia', code: 'MY'}, 
    {name: 'Maldives', code: 'MV'}, 
    {name: 'Mali', code: 'ML'}, 
    {name: 'Malta', code: 'MT'}, 
    {name: 'Marshall Islands', code: 'MH'}, 
    {name: 'Martinique', code: 'MQ'}, 
    {name: 'Mauritania', code: 'MR'}, 
    {name: 'Mauritius', code: 'MU'}, 
    {name: 'Mayotte', code: 'YT'}, 
    {name: 'Mexico', code: 'MX'}, 
    {name: 'Micronesia, Federated States of', code: 'FM'}, 
    {name: 'Moldova, Republic of', code: 'MD'}, 
    {name: 'Monaco', code: 'MC'}, 
    {name: 'Mongolia', code: 'MN'}, 
    {name: 'Montserrat', code: 'MS'}, 
    {name: 'Morocco', code: 'MA'}, 
    {name: 'Mozambique', code: 'MZ'}, 
    {name: 'Myanmar', code: 'MM'}, 
    {name: 'Namibia', code: 'NA'}, 
    {name: 'Nauru', code: 'NR'}, 
    {name: 'Nepal', code: 'NP'}, 
    {name: 'Netherlands', code: 'NL'}, 
    {name: 'Netherlands Antilles', code: 'AN'}, 
    {name: 'New Caledonia', code: 'NC'}, 
    {name: 'New Zealand', code: 'NZ'}, 
    {name: 'Nicaragua', code: 'NI'}, 
    {name: 'Niger', code: 'NE'}, 
    {name: 'Nigeria', code: 'NG'}, 
    {name: 'Niue', code: 'NU'}, 
    {name: 'Norfolk Island', code: 'NF'}, 
    {name: 'Northern Mariana Islands', code: 'MP'}, 
    {name: 'Norway', code: 'NO'}, 
    {name: 'Oman', code: 'OM'}, 
    {name: 'Pakistan', code: 'PK'}, 
    {name: 'Palau', code: 'PW'}, 
    {name: 'Palestinian Territory, Occupied', code: 'PS'}, 
    {name: 'Panama', code: 'PA'}, 
    {name: 'Papua New Guinea', code: 'PG'}, 
    {name: 'Paraguay', code: 'PY'}, 
    {name: 'Peru', code: 'PE'}, 
    {name: 'Philippines', code: 'PH'}, 
    {name: 'Pitcairn', code: 'PN'}, 
    {name: 'Poland', code: 'PL'}, 
    {name: 'Portugal', code: 'PT'}, 
    {name: 'Puerto Rico', code: 'PR'}, 
    {name: 'Qatar', code: 'QA'}, 
    {name: 'Reunion', code: 'RE'}, 
    {name: 'Romania', code: 'RO'}, 
    {name: 'Russian Federation', code: 'RU'}, 
    {name: 'RWANDA', code: 'RW'}, 
    {name: 'Saint Helena', code: 'SH'}, 
    {name: 'Saint Kitts and Nevis', code: 'KN'}, 
    {name: 'Saint Lucia', code: 'LC'}, 
    {name: 'Saint Pierre and Miquelon', code: 'PM'}, 
    {name: 'Saint Vincent and the Grenadines', code: 'VC'}, 
    {name: 'Samoa', code: 'WS'}, 
    {name: 'San Marino', code: 'SM'}, 
    {name: 'Sao Tome and Principe', code: 'ST'}, 
    {name: 'Saudi Arabia', code: 'SA'}, 
    {name: 'Senegal', code: 'SN'}, 
    {name: 'Serbia and Montenegro', code: 'CS'}, 
    {name: 'Seychelles', code: 'SC'}, 
    {name: 'Sierra Leone', code: 'SL'}, 
    {name: 'Singapore', code: 'SG'}, 
    {name: 'Slovakia', code: 'SK'}, 
    {name: 'Slovenia', code: 'SI'}, 
    {name: 'Solomon Islands', code: 'SB'}, 
    {name: 'Somalia', code: 'SO'}, 
    {name: 'South Africa', code: 'ZA'}, 
    {name: 'South Georgia and the South Sandwich Islands', code: 'GS'}, 
    {name: 'Spain', code: 'ES'}, 
    {name: 'Sri Lanka', code: 'LK'}, 
    {name: 'Sudan', code: 'SD'}, 
    {name: 'Suriname', code: 'SR'}, 
    {name: 'Svalbard and Jan Mayen', code: 'SJ'}, 
    {name: 'Swaziland', code: 'SZ'}, 
    {name: 'Sweden', code: 'SE'}, 
    {name: 'Switzerland', code: 'CH'}, 
    {name: 'Syrian Arab Republic', code: 'SY'}, 
    {name: 'Taiwan, Province of China', code: 'TW'}, 
    {name: 'Tajikistan', code: 'TJ'}, 
    {name: 'Tanzania, United Republic of', code: 'TZ'}, 
    {name: 'Thailand', code: 'TH'}, 
    {name: 'Timor-Leste', code: 'TL'}, 
    {name: 'Togo', code: 'TG'}, 
    {name: 'Tokelau', code: 'TK'}, 
    {name: 'Tonga', code: 'TO'}, 
    {name: 'Trinidad and Tobago', code: 'TT'}, 
    {name: 'Tunisia', code: 'TN'}, 
    {name: 'Turkey', code: 'TR'}, 
    {name: 'Turkmenistan', code: 'TM'}, 
    {name: 'Turks and Caicos Islands', code: 'TC'}, 
    {name: 'Tuvalu', code: 'TV'}, 
    {name: 'Uganda', code: 'UG'}, 
    {name: 'Ukraine', code: 'UA'}, 
    {name: 'United Arab Emirates', code: 'AE'}, 
    {name: 'United Kingdom', code: 'GB'}, 
    {name: 'United States', code: 'US'}, 
    {name: 'United States Minor Outlying Islands', code: 'UM'}, 
    {name: 'Uruguay', code: 'UY'}, 
    {name: 'Uzbekistan', code: 'UZ'}, 
    {name: 'Vanuatu', code: 'VU'}, 
    {name: 'Venezuela', code: 'VE'}, 
    {name: 'Viet Nam', code: 'VN'}, 
    {name: 'Virgin Islands, British', code: 'VG'}, 
    {name: 'Virgin Islands, U.S.', code: 'VI'}, 
    {name: 'Wallis and Futuna', code: 'WF'}, 
    {name: 'Western Sahara', code: 'EH'}, 
    {name: 'Yemen', code: 'YE'}, 
    {name: 'Zambia', code: 'ZM'}, 
    {name: 'Zimbabwe', code: 'ZW'} 
  ]

  export const currencyData = [
      {
        country: "US",
        name: "USD",
        value: "0.0022",
        code: "NGN",
        codeValue: "0.0023",
        trend: "down",
        trendValue: "-2.08%",
      },
      {
        country: "GB",
        name: "GBP",
        value: "0.0018",
        code: "NGN",
        codeValue: "0.0015",
        trend: "up",
        trendValue: "+2.01%",
      },
      {
        country: "CA",
        name: "CAD",
        value: "0.0030",
        code: "NGN",
        codeValue: "0.0032",
        trend: "down",
        trendValue: "-2.10%",
      },
      {
        country: "EU",
        name: "EUR",
        value: "0.0020",
        code: "NGN",
        codeValue: "0.0018",
        trend: "up",
        trendValue: "+1.12%",
      },
  ];

  type GroupData = {
    id: number;
    name: string;
    imageUrl: string;
    deposit: string;
    depositType: "increase" | "decrease" | undefined;
    depositStat: string;
    received: string;
    receiveType: "increase" | "decrease" | undefined;
    receiveStat: string

  }
  export const groups: GroupData[] = [
    {
      id: 1,
      name: "Uchiha Investment",
      imageUrl: "https://assets.myket.ir/icons/large/d0e601f5-64d5-4346-b0a7-c76e4f051162.png",
      deposit: "3,500",
      received: "500",
      depositType: "increase",
      receiveType: "decrease",
      depositStat: "3.30%",
      receiveStat: "4.55%"
    },
    {
      id: 2,
      name: "C307 Roommates",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVC0obXDEqzqI55aulb2jmlvNvaqN2XPcEdQ&usqp=CAU",
      deposit: "25,150",
      received: "12,550",
      depositType: "decrease",
      receiveType: "decrease",
      depositStat: "2.49%",
      receiveStat: "2.47%"
    },
    {
      id: 3,
      name: "Joseph Seed Violin Lessons",
      imageUrl: "https://i.pravatar.cc/70?img=55",
      deposit: "5,750",
      received: "1,300",
      depositType: "increase",
      receiveType: "increase",
      depositStat: "6.60%",
      receiveStat: "10.05%"
    },
    {
      id: 4,
      name: "Donate NGO",
      imageUrl: "https://img.freepik.com/premium-vector/n-g-o-logo-design-charity_652297-1010.jpg?w=2000",
      deposit: "34,600",
      received: "3,0  00",
      depositType: "increase",
      receiveType: "decrease",
      depositStat: "23.36%",
      receiveStat: "9.05%"
    },
    {
      id: 5,
      name: "CODM Wallet",
      imageUrl: "https://i.pinimg.com/originals/42/fe/37/42fe37e7428573b1cdf2824a500c580b.jpg",
      deposit: "10,750",
      received: "3,500",
      depositType: "increase",
      receiveType: "decrease",
      depositStat: "23.36%",
      receiveStat: "9.05%"
    },
  ];

  type SubsData = {
    id: number;
    name: string;
    imageUrl: string;
    deposit: string;
    depositType: "increase" | "decrease" | undefined;
    depositStat: string;
  }
  export const subscriptions: SubsData[] = [
    {
      id: 1,
      name: "Netflix",
      imageUrl: "https://s3-alpha.figma.com/hub/file/2748081035/1ddb18ac-1a21-4703-bc54-4c4c71aafc2e-cover.png",
      deposit: "4,600",
      depositType: "increase",
      depositStat: "0.51%",
    },
    {
      id: 2,
      name: "Spotify Premium",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Spotify_App_Logo.svg/2048px-Spotify_App_Logo.svg.png",
      deposit: "900",
      depositType: "decrease",
      depositStat: "1.20%",
    },
    {
      id: 3,
      name: "OpenAI ChatGPT Plus",
      imageUrl: "https://mrvian.com/wp-content/uploads/2023/02/logo-open-ai.png",
      deposit: "9,200",
      depositType: "increase",
      depositStat: "0.60%",
    },
    {
      id: 4,
      name: "DSTV Compact Package",
      imageUrl: "https://www.dstv.com/media/kt2lleca/dstv_website_preview_thumbnail.png?anchor=center&mode=crop&width=1200&height=630&rnd=132883618110400000",
      deposit: "9,000",
      depositType: "increase",
      depositStat: "0.02%",
    },
  ];

  export const invites = [
    {
      id: 1,
      name: "Camelo Candy",
      imageUrl: "https://i.pravatar.cc/70?img=9",
    },
    {
      id: 2,
      name: "Charles Harper",
      imageUrl: "https://i.pravatar.cc/70?img=58",
    },
    {
      id: 3,
      name: "Jack Barker",
      imageUrl: "https://i.pravatar.cc/70?img=69",
    },
    {
      id: 4,
      name: "Richard Hendricks",
      imageUrl: "https://i.pravatar.cc/70?img=64",
    },
    {
      id: 5,
      name: "Miles Spector",
      imageUrl: "https://i.pravatar.cc/70?img=50",
    },
    {
      id: 6,
      name: "Tobiloba Adesayo",
      imageUrl: "https://i.pravatar.cc/70?img=38",
    },
  ];

  export const approvedLoans = [
    {
      id: 1,
      name: "Erica Thompson",
      imageUrl: "https://i.pravatar.cc/70?img=19",
      time: "30 mins ago",
      amount: "30,000",
      tag: "Quick Loan"
    },
    {
      id: 2,
      name: "Leonard Cooper",
      imageUrl: "https://i.pravatar.cc/70?img=6",
      time: "12 hrs ago",
      amount: "45,000",
      tag: "Quick Loan"
    },
    {
      id: 3,
      name: "Gavin Belson",
      imageUrl: "https://i.pravatar.cc/70?img=14",
      time: "2 days ago",
      amount: "260,000",
      tag: "Quick Loan"
    },
  ];

  export const requestsLoans = [
    {
      id: 1,
      name: "Jemima Udoumoh",
      imageUrl: "https://img.freepik.com/free-photo/sideways-shot-adorable-young-female-with-dark-skin-looks-seriously-confidently-shows-her-natural-beauty-poses-fashion-magazine-wears-round-glasses-casual-t-shirt_273609-15638.jpg?w=740",
      time: "30 mins ago",
      amount: "130,000",
      tag: "Quick Loan"
    },
    {
      id: 2,
      name: "Ibrahim Ali",
      imageUrl: "https://i.pravatar.cc/70?img=59",
      time: "4 days ago",
      amount: "45,000",
      tag: "Quick Loan"
    },
    {
      id: 3,
      name: "Eric Bachmann",
      imageUrl: "https://i.pravatar.cc/70?img=52",
      time: "11 days ago",
      amount: "20,000",
      tag: "Quick Loan"
    },
    {
      id: 4,
      name: "Sarah Bucks",
      imageUrl: "https://i.pravatar.cc/70?img=45",
      time: "2 weeks ago",
      amount: "12,000",
      tag: "Quick Loan"
    },
  ];

  
  type AvatarData = {
    id: number;
    name: string;
    imageUrl: string;
    border?: string;
  };
  
  export const initialData: AvatarData[] = [
    {
      id: 1,
      name: "ibrahim.ali",
      imageUrl: "https://i.pravatar.cc/70?img=59",
      border: "red",
    },
    {
      id: 2,
      name: "mr.bachmann",
      imageUrl: "https://i.pravatar.cc/70?img=52",
      border: "#400050",
    },
    {
      id: 3,
      name: "s_bucks",
      imageUrl: "https://i.pravatar.cc/70?img=45",
      border: "#400050",
    },
    {
      id: 4,
      name: "jemma123",
      imageUrl: "https://img.freepik.com/free-photo/sideways-shot-adorable-young-female-with-dark-skin-looks-seriously-confidently-shows-her-natural-beauty-poses-fashion-magazine-wears-round-glasses-casual-t-shirt_273609-15638.jpg?w=740",
      border: "green",
    },
    {
      id: 5,
      name: "gavinb__",
      imageUrl: "https://i.pravatar.cc/70?img=14",
      border: "#400050",
    },
    {
      id: 6,
      name: "dr.lcooper",
      imageUrl: "https://i.pravatar.cc/70?img=6",
      border: "#400050",
    },
    {
      id: 7,
      name: "erica_spending",
      imageUrl: "https://i.pravatar.cc/70?img=19",
      border: "red",
    },
    {
      id: 8,
      name: "kunle_fx",
      imageUrl: "https://img.freepik.com/free-photo/portrait-good-looking-man-smiling_23-2148780106.jpg?w=360",
      border: "green",
    },
    {
      id: 9,
      name: "ch1n3du",
      imageUrl: "https://i.pravatar.cc/70?img=11",
      border: "#400050",
    },
  ];

  export const sentLoans = [
    {
      id: 1,
      name: "Adekunle Ajayi",
      imageUrl: "https://img.freepik.com/free-photo/portrait-good-looking-man-smiling_23-2148780106.jpg?w=360",
      time: "46 mins ago",
      amount: "1,500",
      tag: "MTN Data Plan"
    },
    {
      id: 2,
      name: "Quasar Payments",
      imageUrl: "/qpsicon.png",
      time: "4 days ago",
      amount: "1,750,000",
      tag: "Mid Term Loan"
    },
  ];
